sudo: false
dist: trusty
language: node_js
node_js:
  - 6
  - 8
  - 9
  - node

cache:
  directories:
    - node_modules

notifications:
  email:
    on_failure: change

before_install:
  - npm install -g npm@latest

install:
  - npm ci

script:
  - npm run clean
  - npm run build
  - npm run bundle
  - npm run test
